"""Initial game world schema

Revision ID: 1706a93ccd41
Revises:
Create Date: 2026-03-25 12:28:29.135638

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1706a93ccd41"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "engine_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("due_tick", sa.Integer(), nullable=False),
        sa.Column("context_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    op.create_table(
        "federations",
        sa.Column("federation_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("tier", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("federation_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_federations_owner_user_id"),
        "federations",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "narrative_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tick_id", sa.String(), nullable=False),
        sa.Column("time_index", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "worlds",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_multiplayer", sa.Boolean(), nullable=True),
        sa.Column("max_players", sa.Integer(), nullable=True),
        sa.Column("current_game_date", sa.String(length=10), nullable=True),
        sa.Column("current_tick", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("world_config", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agents",
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("gimmick_description", sa.Text(), nullable=False),
        sa.Column("llm_config", sa.JSON(), nullable=False),
        sa.Column("federation_id", sa.String(), nullable=True),
        sa.Column("current_heat", sa.Integer(), nullable=True),
        sa.Column("momentum", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["federation_id"],
            ["federations.federation_id"],
        ),
        sa.PrimaryKeyConstraint("agent_id"),
    )
    op.create_index(op.f("ix_agents_user_id"), "agents", ["user_id"], unique=False)
    op.create_table(
        "game_federations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("world_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("short_name", sa.String(length=10), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_npc", sa.Boolean(), nullable=True),
        sa.Column("prestige", sa.Integer(), nullable=True),
        sa.Column("budget", sa.Float(), nullable=True),
        sa.Column("weekly_revenue", sa.Float(), nullable=True),
        sa.Column("weekly_expenses", sa.Float(), nullable=True),
        sa.Column("tv_deal_value", sa.Float(), nullable=True),
        sa.Column("home_region", sa.String(length=50), nullable=True),
        sa.Column("style", sa.String(length=50), nullable=True),
        sa.Column("founded_date", sa.String(length=10), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("ai_personality", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["worlds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("world_id", "name", name="uq_federation_name_world"),
    )
    op.create_index(
        op.f("ix_game_federations_world_id"),
        "game_federations",
        ["world_id"],
        unique=False,
    )
    op.create_table(
        "game_narrative_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("world_id", sa.String(), nullable=False),
        sa.Column("game_date", sa.String(length=10), nullable=False),
        sa.Column("tick", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("involved_entities", sa.JSON(), nullable=True),
        sa.Column("importance", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["worlds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_narrative_logs_world_id"),
        "game_narrative_logs",
        ["world_id"],
        unique=False,
    )
    op.create_index(
        "ix_narrative_world_date",
        "game_narrative_logs",
        ["world_id", "game_date"],
        unique=False,
    )
    op.create_table(
        "game_wrestlers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("world_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("real_name", sa.String(length=100), nullable=True),
        sa.Column("is_npc", sa.Boolean(), nullable=True),
        sa.Column("gimmick", sa.Text(), nullable=True),
        sa.Column("alignment", sa.String(length=20), nullable=True),
        sa.Column("popularity", sa.Integer(), nullable=True),
        sa.Column("condition", sa.Integer(), nullable=True),
        sa.Column("morale", sa.Integer(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("experience_years", sa.Integer(), nullable=True),
        sa.Column("gender", sa.String(length=20), nullable=True),
        sa.Column("weight_class", sa.String(length=20), nullable=True),
        sa.Column("hometown", sa.String(length=100), nullable=True),
        sa.Column("entrance_music", sa.String(length=200), nullable=True),
        sa.Column("finisher_name", sa.String(length=100), nullable=True),
        sa.Column("finisher_type", sa.String(length=50), nullable=True),
        sa.Column("signature_moves", sa.JSON(), nullable=True),
        sa.Column("catchphrase", sa.String(length=200), nullable=True),
        sa.Column("personality_traits", sa.JSON(), nullable=True),
        sa.Column("career_goals", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_injured", sa.Boolean(), nullable=True),
        sa.Column("injury_return_date", sa.String(length=10), nullable=True),
        sa.Column("debut_date", sa.String(length=10), nullable=True),
        sa.Column("retirement_date", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["worlds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_wrestlers_world_id"), "game_wrestlers", ["world_id"], unique=False
    )
    op.create_table(
        "world_news",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("world_id", sa.String(), nullable=False),
        sa.Column("headline", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=True),
        sa.Column("game_date", sa.String(length=10), nullable=False),
        sa.Column("is_kayfabe", sa.Boolean(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("related_entities", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["worlds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_world_news_world_id"), "world_news", ["world_id"], unique=False
    )
    op.create_table(
        "world_state",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("world_id", sa.String(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["worlds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("world_id", "key", name="uq_world_state_key"),
    )
    op.create_index(
        op.f("ix_world_state_world_id"), "world_state", ["world_id"], unique=False
    )
    op.create_table(
        "championships",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("world_id", sa.String(), nullable=False),
        sa.Column("federation_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("prestige", sa.Integer(), nullable=True),
        sa.Column("weight_class", sa.String(length=20), nullable=True),
        sa.Column("is_tag_team", sa.Boolean(), nullable=True),
        sa.Column("current_holder_id", sa.String(), nullable=True),
        sa.Column("current_reign_start", sa.String(length=10), nullable=True),
        sa.Column("defenses", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["current_holder_id"],
            ["game_wrestlers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["federation_id"],
            ["game_federations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["worlds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_championships_federation_id"),
        "championships",
        ["federation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_championships_world_id"), "championships", ["world_id"], unique=False
    )
    op.create_table(
        "contracts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("world_id", sa.String(), nullable=False),
        sa.Column("wrestler_id", sa.String(), nullable=False),
        sa.Column("federation_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("salary_weekly", sa.Float(), nullable=True),
        sa.Column("start_date", sa.String(length=10), nullable=False),
        sa.Column("end_date", sa.String(length=10), nullable=True),
        sa.Column("is_exclusive", sa.Boolean(), nullable=True),
        sa.Column("merchandise_split", sa.Float(), nullable=True),
        sa.Column("downside_guarantee", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["federation_id"],
            ["game_federations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["worlds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wrestler_id"],
            ["game_wrestlers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contracts_federation_id"), "contracts", ["federation_id"], unique=False
    )
    op.create_index(
        op.f("ix_contracts_world_id"), "contracts", ["world_id"], unique=False
    )
    op.create_index(
        op.f("ix_contracts_wrestler_id"), "contracts", ["wrestler_id"], unique=False
    )
    op.create_table(
        "players",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("world_id", sa.String(), nullable=False),
        sa.Column("player_type", sa.String(length=20), nullable=False),
        sa.Column("federation_id", sa.String(), nullable=True),
        sa.Column("wrestler_id", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["federation_id"],
            ["game_federations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["worlds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wrestler_id"],
            ["game_wrestlers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "world_id", name="uq_player_user_world"),
    )
    op.create_index(op.f("ix_players_user_id"), "players", ["user_id"], unique=False)
    op.create_index(op.f("ix_players_world_id"), "players", ["world_id"], unique=False)
    op.create_table(
        "promos",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("world_id", sa.String(), nullable=False),
        sa.Column("wrestler_id", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("target_wrestler_id", sa.String(), nullable=True),
        sa.Column("promo_type", sa.String(length=30), nullable=True),
        sa.Column("crowd_reaction", sa.String(length=30), nullable=True),
        sa.Column("heat_generated", sa.Integer(), nullable=True),
        sa.Column("quality_rating", sa.Float(), nullable=True),
        sa.Column("game_date", sa.String(length=10), nullable=True),
        sa.Column("is_player_written", sa.Boolean(), nullable=True),
        sa.Column("player_direction", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["target_wrestler_id"],
            ["game_wrestlers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["worlds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wrestler_id"],
            ["game_wrestlers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_promos_world_id"), "promos", ["world_id"], unique=False)
    op.create_index(
        op.f("ix_promos_wrestler_id"), "promos", ["wrestler_id"], unique=False
    )
    op.create_table(
        "shows",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("world_id", sa.String(), nullable=False),
        sa.Column("federation_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("show_type", sa.String(length=20), nullable=True),
        sa.Column("venue", sa.String(length=100), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("attendance", sa.Integer(), nullable=True),
        sa.Column("game_date", sa.String(length=10), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=True),
        sa.Column("overall_rating", sa.Float(), nullable=True),
        sa.Column("tv_rating", sa.Float(), nullable=True),
        sa.Column("gate_revenue", sa.Float(), nullable=True),
        sa.Column("ppv_buys", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["federation_id"],
            ["game_federations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["worlds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shows_federation_id"), "shows", ["federation_id"], unique=False
    )
    op.create_index(op.f("ix_shows_world_id"), "shows", ["world_id"], unique=False)
    op.create_table(
        "storylines",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("world_id", sa.String(), nullable=False),
        sa.Column("federation_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("storyline_type", sa.String(length=30), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("heat", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.String(length=10), nullable=True),
        sa.Column("end_date", sa.String(length=10), nullable=True),
        sa.Column("planned_blowoff", sa.Text(), nullable=True),
        sa.Column("ai_notes", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["federation_id"],
            ["game_federations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["worlds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_storylines_world_id"), "storylines", ["world_id"], unique=False
    )
    op.create_table(
        "wrestler_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wrestler_id", sa.String(), nullable=False),
        sa.Column("game_date", sa.String(length=10), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["wrestler_id"],
            ["game_wrestlers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wrestler_history_wrestler_id"),
        "wrestler_history",
        ["wrestler_id"],
        unique=False,
    )
    op.create_table(
        "wrestler_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wrestler_id", sa.String(), nullable=False),
        sa.Column("power", sa.Integer(), nullable=True),
        sa.Column("speed", sa.Integer(), nullable=True),
        sa.Column("technical", sa.Integer(), nullable=True),
        sa.Column("aerial", sa.Integer(), nullable=True),
        sa.Column("brawling", sa.Integer(), nullable=True),
        sa.Column("submission", sa.Integer(), nullable=True),
        sa.Column("stamina", sa.Integer(), nullable=True),
        sa.Column("toughness", sa.Integer(), nullable=True),
        sa.Column("charisma", sa.Integer(), nullable=True),
        sa.Column("mic_skill", sa.Integer(), nullable=True),
        sa.Column("psychology", sa.Integer(), nullable=True),
        sa.Column("selling", sa.Integer(), nullable=True),
        sa.Column("backstage_politics", sa.Integer(), nullable=True),
        sa.Column("loyalty", sa.Integer(), nullable=True),
        sa.Column("work_ethic", sa.Integer(), nullable=True),
        sa.Column("injury_prone", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["wrestler_id"],
            ["game_wrestlers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wrestler_id"),
    )
    op.create_table(
        "championship_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("championship_id", sa.String(), nullable=False),
        sa.Column("wrestler_id", sa.String(), nullable=False),
        sa.Column("reign_start", sa.String(length=10), nullable=False),
        sa.Column("reign_end", sa.String(length=10), nullable=True),
        sa.Column("defenses", sa.Integer(), nullable=True),
        sa.Column("how_won", sa.String(length=50), nullable=True),
        sa.Column("how_lost", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["championship_id"],
            ["championships.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wrestler_id"],
            ["game_wrestlers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_championship_history_championship_id"),
        "championship_history",
        ["championship_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_championship_history_wrestler_id"),
        "championship_history",
        ["wrestler_id"],
        unique=False,
    )
    op.create_table(
        "matches",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("world_id", sa.String(), nullable=False),
        sa.Column("match_type", sa.String(length=30), nullable=True),
        sa.Column("stipulation", sa.String(length=100), nullable=True),
        sa.Column("is_title_match", sa.Boolean(), nullable=True),
        sa.Column("championship_id", sa.String(), nullable=True),
        sa.Column("winner_id", sa.String(), nullable=True),
        sa.Column("finish_type", sa.String(length=30), nullable=True),
        sa.Column("finish_description", sa.Text(), nullable=True),
        sa.Column("match_rating", sa.Float(), nullable=True),
        sa.Column("crowd_heat", sa.Integer(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=True),
        sa.Column("simulation_log", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["championship_id"],
            ["championships.id"],
        ),
        sa.ForeignKeyConstraint(
            ["winner_id"],
            ["game_wrestlers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["worlds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_matches_world_id"), "matches", ["world_id"], unique=False)
    op.create_table(
        "player_actions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("world_id", sa.String(), nullable=False),
        sa.Column("player_id", sa.String(), nullable=False),
        sa.Column("action_type", sa.String(length=30), nullable=False),
        sa.Column("action_data", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["worlds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_player_actions_pending",
        "player_actions",
        ["world_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_actions_player_id"),
        "player_actions",
        ["player_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_actions_world_id"), "player_actions", ["world_id"], unique=False
    )
    op.create_table(
        "storyline_participants",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("storyline_id", sa.String(), nullable=False),
        sa.Column("wrestler_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=True),
        sa.Column("joined_date", sa.String(length=10), nullable=True),
        sa.Column("left_date", sa.String(length=10), nullable=True),
        sa.ForeignKeyConstraint(
            ["storyline_id"],
            ["storylines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wrestler_id"],
            ["game_wrestlers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_storyline_participants_storyline_id"),
        "storyline_participants",
        ["storyline_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_storyline_participants_wrestler_id"),
        "storyline_participants",
        ["wrestler_id"],
        unique=False,
    )
    op.create_table(
        "match_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("tick", sa.Integer(), nullable=False),
        sa.Column("acting_wrestler_id", sa.String(), nullable=True),
        sa.Column("target_wrestler_id", sa.String(), nullable=True),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("crowd_reaction", sa.String(length=30), nullable=True),
        sa.Column("heat_change", sa.Integer(), nullable=True),
        sa.Column("momentum_change", sa.Integer(), nullable=True),
        sa.Column("damage", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["acting_wrestler_id"],
            ["game_wrestlers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_wrestler_id"],
            ["game_wrestlers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_match_events_match_id"), "match_events", ["match_id"], unique=False
    )
    op.create_table(
        "match_participants",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("wrestler_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=True),
        sa.Column("team", sa.Integer(), nullable=True),
        sa.Column("is_winner", sa.Boolean(), nullable=True),
        sa.Column("performance_rating", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wrestler_id"],
            ["game_wrestlers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_match_participants_match_id"),
        "match_participants",
        ["match_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_match_participants_wrestler_id"),
        "match_participants",
        ["wrestler_id"],
        unique=False,
    )
    op.create_table(
        "show_segments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("show_id", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("segment_type", sa.String(length=20), nullable=False),
        sa.Column("match_id", sa.String(), nullable=True),
        sa.Column("promo_id", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("planned_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("actual_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("crowd_reaction", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["promo_id"],
            ["promos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["show_id"],
            ["shows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_show_segments_show_id"), "show_segments", ["show_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_show_segments_show_id"), table_name="show_segments")
    op.drop_table("show_segments")
    op.drop_index(
        op.f("ix_match_participants_wrestler_id"), table_name="match_participants"
    )
    op.drop_index(
        op.f("ix_match_participants_match_id"), table_name="match_participants"
    )
    op.drop_table("match_participants")
    op.drop_index(op.f("ix_match_events_match_id"), table_name="match_events")
    op.drop_table("match_events")
    op.drop_index(
        op.f("ix_storyline_participants_wrestler_id"),
        table_name="storyline_participants",
    )
    op.drop_index(
        op.f("ix_storyline_participants_storyline_id"),
        table_name="storyline_participants",
    )
    op.drop_table("storyline_participants")
    op.drop_index(op.f("ix_player_actions_world_id"), table_name="player_actions")
    op.drop_index(op.f("ix_player_actions_player_id"), table_name="player_actions")
    op.drop_index("ix_player_actions_pending", table_name="player_actions")
    op.drop_table("player_actions")
    op.drop_index(op.f("ix_matches_world_id"), table_name="matches")
    op.drop_table("matches")
    op.drop_index(
        op.f("ix_championship_history_wrestler_id"), table_name="championship_history"
    )
    op.drop_index(
        op.f("ix_championship_history_championship_id"),
        table_name="championship_history",
    )
    op.drop_table("championship_history")
    op.drop_table("wrestler_stats")
    op.drop_index(
        op.f("ix_wrestler_history_wrestler_id"), table_name="wrestler_history"
    )
    op.drop_table("wrestler_history")
    op.drop_index(op.f("ix_storylines_world_id"), table_name="storylines")
    op.drop_table("storylines")
    op.drop_index(op.f("ix_shows_world_id"), table_name="shows")
    op.drop_index(op.f("ix_shows_federation_id"), table_name="shows")
    op.drop_table("shows")
    op.drop_index(op.f("ix_promos_wrestler_id"), table_name="promos")
    op.drop_index(op.f("ix_promos_world_id"), table_name="promos")
    op.drop_table("promos")
    op.drop_index(op.f("ix_players_world_id"), table_name="players")
    op.drop_index(op.f("ix_players_user_id"), table_name="players")
    op.drop_table("players")
    op.drop_index(op.f("ix_contracts_wrestler_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_world_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_federation_id"), table_name="contracts")
    op.drop_table("contracts")
    op.drop_index(op.f("ix_championships_world_id"), table_name="championships")
    op.drop_index(op.f("ix_championships_federation_id"), table_name="championships")
    op.drop_table("championships")
    op.drop_index(op.f("ix_world_state_world_id"), table_name="world_state")
    op.drop_table("world_state")
    op.drop_index(op.f("ix_world_news_world_id"), table_name="world_news")
    op.drop_table("world_news")
    op.drop_index(op.f("ix_game_wrestlers_world_id"), table_name="game_wrestlers")
    op.drop_table("game_wrestlers")
    op.drop_index("ix_narrative_world_date", table_name="game_narrative_logs")
    op.drop_index(
        op.f("ix_game_narrative_logs_world_id"), table_name="game_narrative_logs"
    )
    op.drop_table("game_narrative_logs")
    op.drop_index(op.f("ix_game_federations_world_id"), table_name="game_federations")
    op.drop_table("game_federations")
    op.drop_index(op.f("ix_agents_user_id"), table_name="agents")
    op.drop_table("agents")
    op.drop_table("worlds")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("narrative_logs")
    op.drop_index(op.f("ix_federations_owner_user_id"), table_name="federations")
    op.drop_table("federations")
    op.drop_table("engine_requests")
    # ### end Alembic commands ###
