"""fix_schema_drift

Revision ID: 3313c01b8b58
Revises: abc0cf32b69a
Create Date: 2026-10-02 17:40:26.414604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3313c01b8b58'
down_revision: Union[str, Sequence[str], None] = 'abc0cf32b69a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_wrestlers', schema=None) as batch_op:
        batch_op.alter_column('win_streak',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_wrestlers', schema=None) as batch_op:
        batch_op.alter_column('win_streak',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
