"""Add missing columns and tables

Revision ID: abc0cf32b69a
Revises: a1b2c3d4e5f6
Create Date: 2026-09-30 17:16:16.753119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc0cf32b69a'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(), nullable=False),
                    sa.Column('entity_type', sa.String(length=50), nullable=False),
                    sa.Column('entity_id', sa.String(), nullable=False),
                    sa.Column('field_name', sa.String(length=100), nullable=False),
                    sa.Column('action', sa.String(length=20), nullable=False),
                    sa.Column('old_value', sa.JSON(), nullable=True),
                    sa.Column('new_value', sa.JSON(), nullable=True),
                    sa.Column('actor_type', sa.String(length=30), nullable=True),
                    sa.Column('actor_id', sa.String(), nullable=True),
                    sa.Column('world_id', sa.String(), nullable=True),
                    sa.Column('reason', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_world_id'), 'audit_log', ['world_id'], unique=False)
    op.create_index('ix_audit_world_ts', 'audit_log', ['world_id', 'timestamp'], unique=False)
    op.create_table('booking_visions',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('world_id', sa.String(), nullable=False),
                    sa.Column('federation_id', sa.String(), nullable=False),
                    sa.Column('identity', sa.String(length=200), nullable=True),
                    sa.Column('long_term_goal', sa.String(length=200), nullable=True),
                    sa.Column('crown_jewel_vision', sa.JSON(), nullable=True),
                    sa.Column('push_tiers', sa.JSON(), nullable=True),
                    sa.Column('trajectories', sa.JSON(), nullable=True),
                    sa.Column('title_pipelines', sa.JSON(), nullable=True),
                    sa.Column('planned_storylines', sa.JSON(), nullable=True),
                    sa.Column('adaptation_log', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['federation_id'], ['game_federations.id'], ),
                    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('federation_id')
                    )
    op.create_index(op.f('ix_booking_visions_world_id'), 'booking_visions', ['world_id'], unique=False)
    op.create_table('gimmick_history',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('wrestler_id', sa.String(), nullable=False),
                    sa.Column('gimmick_name', sa.String(length=100), nullable=False),
                    sa.Column('archetype', sa.String(length=30), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('origin_narrative', sa.Text(), nullable=True),
                    sa.Column('alignment', sa.String(length=20), nullable=True),
                    sa.Column('voice_style', sa.JSON(), nullable=True),
                    sa.Column('visual_identity', sa.JSON(), nullable=True),
                    sa.Column('start_date', sa.String(length=10), nullable=True),
                    sa.Column('end_date', sa.String(length=10), nullable=True),
                    sa.Column('depth_score', sa.Integer(), nullable=True),
                    sa.Column('effectiveness', sa.Integer(), nullable=True),
                    sa.Column('staleness', sa.Integer(), nullable=True),
                    sa.Column('fan_investment', sa.Integer(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('reason_for_change', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['wrestler_id'], ['game_wrestlers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_gimmick_history_wrestler_id'), 'gimmick_history', ['wrestler_id'], unique=False)
    op.create_table('hall_of_fame',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('world_id', sa.String(), nullable=False),
                    sa.Column('wrestler_id', sa.String(), nullable=False),
                    sa.Column('inducted_date', sa.String(length=10), nullable=False),
                    sa.Column('legacy_score', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
                    sa.ForeignKeyConstraint(['wrestler_id'], ['game_wrestlers.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('world_id', 'wrestler_id', name='uq_hof_wrestler')
                    )
    op.create_index(op.f('ix_hall_of_fame_world_id'), 'hall_of_fame', ['world_id'], unique=False)
    op.create_index(op.f('ix_hall_of_fame_wrestler_id'), 'hall_of_fame', ['wrestler_id'], unique=False)
    op.create_table('life_events',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('wrestler_id', sa.String(), nullable=False),
                    sa.Column('world_id', sa.String(), nullable=False),
                    sa.Column('game_date', sa.String(length=10), nullable=False),
                    sa.Column('event_type', sa.String(length=30), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('severity', sa.Integer(), nullable=True),
                    sa.Column('is_public', sa.Boolean(), nullable=True),
                    sa.Column('morale_impact', sa.Integer(), nullable=True),
                    sa.Column('performance_impact', sa.Integer(), nullable=True),
                    sa.Column('storyline_potential', sa.Boolean(), nullable=True),
                    sa.Column('was_used_in_storyline', sa.Boolean(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('resolved_date', sa.String(length=10), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
                    sa.ForeignKeyConstraint(['wrestler_id'], ['game_wrestlers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_life_event_world_date', 'life_events', ['world_id', 'game_date'], unique=False)
    op.create_index(op.f('ix_life_events_world_id'), 'life_events', ['world_id'], unique=False)
    op.create_index(op.f('ix_life_events_wrestler_id'), 'life_events', ['wrestler_id'], unique=False)
    op.create_table('managers',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('world_id', sa.String(), nullable=False),
                    sa.Column('federation_id', sa.String(), nullable=True),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('real_name', sa.String(length=100), nullable=True),
                    sa.Column('gender', sa.String(length=10), nullable=True),
                    sa.Column('alignment', sa.String(length=10), nullable=True),
                    sa.Column('archetype', sa.String(length=30), nullable=True),
                    sa.Column('personality_traits', sa.JSON(), nullable=True),
                    sa.Column('catchphrase', sa.String(length=200), nullable=True),
                    sa.Column('entrance_music', sa.String(length=100), nullable=True),
                    sa.Column('charisma', sa.Integer(), nullable=True),
                    sa.Column('mic_skill', sa.Integer(), nullable=True),
                    sa.Column('cunning', sa.Integer(), nullable=True),
                    sa.Column('interference_skill', sa.Integer(), nullable=True),
                    sa.Column('can_wrestle', sa.Boolean(), nullable=True),
                    sa.Column('power', sa.Integer(), nullable=True),
                    sa.Column('speed', sa.Integer(), nullable=True),
                    sa.Column('toughness', sa.Integer(), nullable=True),
                    sa.Column('popularity', sa.Integer(), nullable=True),
                    sa.Column('heat', sa.Integer(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['federation_id'], ['game_federations.id'], ),
                    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_managers_federation_id'), 'managers', ['federation_id'], unique=False)
    op.create_index(op.f('ix_managers_world_id'), 'managers', ['world_id'], unique=False)
    op.create_table('mentorships',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('world_id', sa.String(), nullable=False),
                    sa.Column('mentor_id', sa.String(), nullable=False),
                    sa.Column('protege_id', sa.String(), nullable=False),
                    sa.Column('federation_id', sa.String(), nullable=False),
                    sa.Column('started_date', sa.String(length=10), nullable=True),
                    sa.Column('ended_date', sa.String(length=10), nullable=True),
                    sa.Column('skill_focus', sa.String(length=30), nullable=True),
                    sa.Column('mentor_bonus', sa.Float(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['federation_id'], ['game_federations.id'], ),
                    sa.ForeignKeyConstraint(['mentor_id'], ['game_wrestlers.id'], ),
                    sa.ForeignKeyConstraint(['protege_id'], ['game_wrestlers.id'], ),
                    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_mentorships_federation_id'), 'mentorships', ['federation_id'], unique=False)
    op.create_index(op.f('ix_mentorships_mentor_id'), 'mentorships', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_mentorships_protege_id'), 'mentorships', ['protege_id'], unique=False)
    op.create_index(op.f('ix_mentorships_world_id'), 'mentorships', ['world_id'], unique=False)
    op.create_table('tag_teams',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('world_id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('wrestler1_id', sa.String(), nullable=False),
                    sa.Column('wrestler2_id', sa.String(), nullable=False),
                    sa.Column('team_chemistry', sa.Integer(), nullable=True),
                    sa.Column('team_finisher_name', sa.String(length=100), nullable=True),
                    sa.Column('wins', sa.Integer(), nullable=True),
                    sa.Column('losses', sa.Integer(), nullable=True),
                    sa.Column('formed_date', sa.String(length=10), nullable=True),
                    sa.Column('dissolved_date', sa.String(length=10), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
                    sa.ForeignKeyConstraint(['wrestler1_id'], ['game_wrestlers.id'], ),
                    sa.ForeignKeyConstraint(['wrestler2_id'], ['game_wrestlers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_tag_teams_world_id'), 'tag_teams', ['world_id'], unique=False)
    op.create_index(op.f('ix_tag_teams_wrestler1_id'), 'tag_teams', ['wrestler1_id'], unique=False)
    op.create_index(op.f('ix_tag_teams_wrestler2_id'), 'tag_teams', ['wrestler2_id'], unique=False)
    op.create_table('talent_offers',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('world_id', sa.String(), nullable=False),
                    sa.Column('federation_id', sa.String(), nullable=False),
                    sa.Column('wrestler_id', sa.String(), nullable=False),
                    sa.Column('salary_offered', sa.Float(), nullable=True),
                    sa.Column('contract_length_weeks', sa.Integer(), nullable=True),
                    sa.Column('status', sa.String(length=20), nullable=True),
                    sa.Column('offered_date', sa.String(length=10), nullable=False),
                    sa.Column('expires_date', sa.String(length=10), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['federation_id'], ['game_federations.id'], ),
                    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
                    sa.ForeignKeyConstraint(['wrestler_id'], ['game_wrestlers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_talent_offers_federation_id'), 'talent_offers', ['federation_id'], unique=False)
    op.create_index(op.f('ix_talent_offers_world_id'), 'talent_offers', ['world_id'], unique=False)
    op.create_index(op.f('ix_talent_offers_wrestler_id'), 'talent_offers', ['wrestler_id'], unique=False)
    op.create_table('wrestler_backstories',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('wrestler_id', sa.String(), nullable=False),
                    sa.Column('origin_story', sa.Text(), nullable=True),
                    sa.Column('family_situation', sa.String(length=50), nullable=True),
                    sa.Column('pre_wrestling_career', sa.String(length=100), nullable=True),
                    sa.Column('wrestling_motivation', sa.String(length=50), nullable=True),
                    sa.Column('real_personality', sa.JSON(), nullable=True),
                    sa.Column('personal_struggles', sa.JSON(), nullable=True),
                    sa.Column('personal_life_stability', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['wrestler_id'], ['game_wrestlers.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('wrestler_id')
                    )
    op.create_table('wrestler_goals',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('wrestler_id', sa.String(), nullable=False),
                    sa.Column('goal_type', sa.String(length=30), nullable=False),
                    sa.Column('target_entity_id', sa.String(), nullable=True),
                    sa.Column('status', sa.String(length=20), nullable=True),
                    sa.Column('progress', sa.Integer(), nullable=True),
                    sa.Column('frustration', sa.Integer(), nullable=True),
                    sa.Column('set_date', sa.String(length=10), nullable=True),
                    sa.Column('completed_date', sa.String(length=10), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['wrestler_id'], ['game_wrestlers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_wrestler_goals_wrestler_id'), 'wrestler_goals', ['wrestler_id'], unique=False)
    op.create_table('wrestler_pushes',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('world_id', sa.String(), nullable=False),
                    sa.Column('federation_id', sa.String(), nullable=False),
                    sa.Column('wrestler_id', sa.String(), nullable=False),
                    sa.Column('push_tier', sa.String(length=20), nullable=True),
                    sa.Column('direction', sa.String(length=20), nullable=True),
                    sa.Column('confidence', sa.Integer(), nullable=True),
                    sa.Column('protected', sa.Boolean(), nullable=True),
                    sa.Column('weeks_at_tier', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['federation_id'], ['game_federations.id'], ),
                    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
                    sa.ForeignKeyConstraint(['wrestler_id'], ['game_wrestlers.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('federation_id', 'wrestler_id', name='uq_push_fed_wrestler')
                    )
    op.create_index(op.f('ix_wrestler_pushes_federation_id'), 'wrestler_pushes', ['federation_id'], unique=False)
    op.create_index(op.f('ix_wrestler_pushes_world_id'), 'wrestler_pushes', ['world_id'], unique=False)
    op.create_index(op.f('ix_wrestler_pushes_wrestler_id'), 'wrestler_pushes', ['wrestler_id'], unique=False)
    op.create_table('wrestler_relationships',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('world_id', sa.String(), nullable=False),
                    sa.Column('wrestler1_id', sa.String(), nullable=False),
                    sa.Column('wrestler2_id', sa.String(), nullable=False),
                    sa.Column('matches_together', sa.Integer(), nullable=True),
                    sa.Column('total_rating', sa.Float(), nullable=True),
                    sa.Column('chemistry_score', sa.Float(), nullable=True),
                    sa.Column('rivalry_heat', sa.Integer(), nullable=True),
                    sa.Column('last_match_date', sa.String(length=10), nullable=True),
                    sa.Column('relationship_type', sa.String(length=20), nullable=True),
                    sa.Column('kayfabe_alignment', sa.String(length=20), nullable=True),
                    sa.Column('real_relationship', sa.String(length=20), nullable=True),
                    sa.Column('trust_level', sa.Integer(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
                    sa.ForeignKeyConstraint(['wrestler1_id'], ['game_wrestlers.id'], ),
                    sa.ForeignKeyConstraint(['wrestler2_id'], ['game_wrestlers.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('world_id', 'wrestler1_id', 'wrestler2_id', name='uq_wrestler_relationship')
                    )
    op.create_index('ix_relationship_pair', 'wrestler_relationships', ['wrestler1_id', 'wrestler2_id'], unique=False)
    op.create_index(op.f('ix_wrestler_relationships_world_id'), 'wrestler_relationships', ['world_id'], unique=False)
    op.create_index(op.f('ix_wrestler_relationships_wrestler1_id'),
                    'wrestler_relationships', ['wrestler1_id'], unique=False)
    op.create_index(op.f('ix_wrestler_relationships_wrestler2_id'),
                    'wrestler_relationships', ['wrestler2_id'], unique=False)
    op.create_table('manager_clients',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('world_id', sa.String(), nullable=False),
                    sa.Column('manager_id', sa.String(), nullable=False),
                    sa.Column('client_wrestler_id', sa.String(), nullable=False),
                    sa.Column('role', sa.String(length=20), nullable=True),
                    sa.Column('effectiveness', sa.Integer(), nullable=True),
                    sa.Column('specialization', sa.String(length=20), nullable=True),
                    sa.Column('charisma_bonus', sa.Integer(), nullable=True),
                    sa.Column('heat_bonus', sa.Integer(), nullable=True),
                    sa.Column('contract_started', sa.String(length=10), nullable=True),
                    sa.Column('contract_ended', sa.String(length=10), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['client_wrestler_id'], ['game_wrestlers.id'], ),
                    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
                    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('manager_id', 'client_wrestler_id', name='uq_manager_client_pair')
                    )
    op.create_index('ix_manager_client_world', 'manager_clients', ['world_id'], unique=False)
    op.create_index(op.f('ix_manager_clients_client_wrestler_id'),
                    'manager_clients', ['client_wrestler_id'], unique=False)
    op.create_index(op.f('ix_manager_clients_manager_id'), 'manager_clients', ['manager_id'], unique=False)
    op.create_index(op.f('ix_manager_clients_world_id'), 'manager_clients', ['world_id'], unique=False)
    op.create_table('ppv_events',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('world_id', sa.String(), nullable=False),
                    sa.Column('federation_id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('theme', sa.String(length=50), nullable=True),
                    sa.Column('scheduled_date', sa.String(length=10), nullable=False),
                    sa.Column('is_crown_jewel', sa.Boolean(), nullable=True),
                    sa.Column('is_completed', sa.Boolean(), nullable=True),
                    sa.Column('show_id', sa.String(), nullable=True),
                    sa.Column('capacity', sa.Integer(), nullable=True),
                    sa.Column('venue', sa.String(length=100), nullable=True),
                    sa.Column('planned_main_event', sa.JSON(), nullable=True),
                    sa.Column('planned_matches', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['federation_id'], ['game_federations.id'], ),
                    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
                    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_ppv_events_federation_id'), 'ppv_events', ['federation_id'], unique=False)
    op.create_index(op.f('ix_ppv_events_world_id'), 'ppv_events', ['world_id'], unique=False)
    op.create_table('social_media_posts',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('wrestler_id', sa.String(), nullable=False),
                    sa.Column('world_id', sa.String(), nullable=False),
                    sa.Column('game_date', sa.String(length=10), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('post_type', sa.String(length=20), nullable=True),
                    sa.Column('platform', sa.String(length=20), nullable=True),
                    sa.Column('engagement_score', sa.Integer(), nullable=True),
                    sa.Column('controversy_level', sa.Integer(), nullable=True),
                    sa.Column('storyline_id', sa.String(), nullable=True),
                    sa.Column('target_wrestler_id', sa.String(), nullable=True),
                    sa.Column('is_viral', sa.Boolean(), nullable=True),
                    sa.Column('fan_reaction', sa.String(length=20), nullable=True),
                    sa.Column('kayfabe_break_level', sa.Integer(), nullable=True),
                    sa.Column('popularity_impact', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['storyline_id'], ['storylines.id'], ),
                    sa.ForeignKeyConstraint(['target_wrestler_id'], ['game_wrestlers.id'], ),
                    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
                    sa.ForeignKeyConstraint(['wrestler_id'], ['game_wrestlers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_social_media_posts_world_id'), 'social_media_posts', ['world_id'], unique=False)
    op.create_index(op.f('ix_social_media_posts_wrestler_id'), 'social_media_posts', ['wrestler_id'], unique=False)
    op.create_index('ix_social_media_world_date', 'social_media_posts', ['world_id', 'game_date'], unique=False)
    op.create_table('stables',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('world_id', sa.String(), nullable=False),
                    sa.Column('federation_id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('short_name', sa.String(length=20), nullable=True),
                    sa.Column('alignment', sa.String(length=10), nullable=True),
                    sa.Column('catchphrase', sa.String(length=200), nullable=True),
                    sa.Column('group_finisher_name', sa.String(length=100), nullable=True),
                    sa.Column('entrance_music', sa.String(length=100), nullable=True),
                    sa.Column('heat', sa.Integer(), nullable=True),
                    sa.Column('prestige', sa.Integer(), nullable=True),
                    sa.Column('dominance', sa.Integer(), nullable=True),
                    sa.Column('cohesion', sa.Integer(), nullable=True),
                    sa.Column('manager_id', sa.String(), nullable=True),
                    sa.Column('formed_date', sa.String(length=10), nullable=True),
                    sa.Column('dissolved_date', sa.String(length=10), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['federation_id'], ['game_federations.id'], ),
                    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
                    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_stable_world_fed', 'stables', ['world_id', 'federation_id'], unique=False)
    op.create_index(op.f('ix_stables_federation_id'), 'stables', ['federation_id'], unique=False)
    op.create_index(op.f('ix_stables_world_id'), 'stables', ['world_id'], unique=False)
    op.create_table('career_highlights',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('wrestler_id', sa.String(), nullable=False),
                    sa.Column('highlight_type', sa.String(length=30), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('game_date', sa.String(length=10), nullable=False),
                    sa.Column('significance', sa.Integer(), nullable=True),
                    sa.Column('match_id', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
                    sa.ForeignKeyConstraint(['wrestler_id'], ['game_wrestlers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_career_highlights_wrestler_id'), 'career_highlights', ['wrestler_id'], unique=False)
    op.create_table('stable_members',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('stable_id', sa.String(), nullable=False),
                    sa.Column('wrestler_id', sa.String(), nullable=False),
                    sa.Column('role', sa.String(length=20), nullable=True),
                    sa.Column('loyalty', sa.Integer(), nullable=True),
                    sa.Column('influence', sa.Integer(), nullable=True),
                    sa.Column('joined_date', sa.String(length=10), nullable=True),
                    sa.Column('left_date', sa.String(length=10), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['stable_id'], ['stables.id'], ),
                    sa.ForeignKeyConstraint(['wrestler_id'], ['game_wrestlers.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('stable_id', 'wrestler_id', name='uq_stable_member_pair')
                    )
    op.create_index(op.f('ix_stable_members_stable_id'), 'stable_members', ['stable_id'], unique=False)
    op.create_index(op.f('ix_stable_members_wrestler_id'), 'stable_members', ['wrestler_id'], unique=False)
    op.create_index(op.f('ix_engine_requests_agent_id'), 'engine_requests', ['agent_id'], unique=False)
    op.create_index(op.f('ix_engine_requests_status'), 'engine_requests', ['status'], unique=False)
    op.add_column('game_federations', sa.Column('market_share', sa.Float(), nullable=True))
    op.add_column('game_federations', sa.Column('momentum', sa.Integer(), nullable=True))
    op.add_column('game_federations', sa.Column('fanbase_loyalty', sa.Integer(), nullable=True))
    op.add_column('game_federations', sa.Column('regional_strength', sa.JSON(), nullable=True))
    op.add_column('game_federations', sa.Column('kayfabe_strictness', sa.Integer(), nullable=True))
    op.add_column('game_federations', sa.Column('allows_worked_shoots', sa.Boolean(), nullable=True))
    op.add_column('game_federations', sa.Column('social_media_policy', sa.String(length=20), nullable=True))
    op.add_column('game_wrestlers', sa.Column('alignment_momentum', sa.Integer(), nullable=True))
    op.add_column('game_wrestlers', sa.Column('draw_rating', sa.Float(), nullable=True))
    op.add_column('game_wrestlers', sa.Column('win_streak', sa.Integer(), nullable=True))
    op.add_column('game_wrestlers', sa.Column('last_booked_date', sa.String(length=10), nullable=True))
    op.add_column('game_wrestlers', sa.Column('birth_date', sa.String(length=10), nullable=True))
    op.add_column('game_wrestlers', sa.Column('peak_age', sa.Integer(), nullable=True))
    op.add_column('game_wrestlers', sa.Column('career_phase', sa.String(length=20), nullable=True))
    op.add_column('game_wrestlers', sa.Column('ring_rust_days', sa.Integer(), nullable=True))
    op.add_column('game_wrestlers', sa.Column('satisfaction', sa.Integer(), nullable=True))
    op.add_column('game_wrestlers', sa.Column('locker_room_standing', sa.String(length=20), nullable=True))
    op.add_column('game_wrestlers', sa.Column('creative_influence', sa.Integer(), nullable=True))
    op.add_column('game_wrestlers', sa.Column('legacy_score', sa.Integer(), nullable=True))
    op.add_column('game_wrestlers', sa.Column('is_hall_of_famer', sa.Boolean(), nullable=True))
    op.add_column('game_wrestlers', sa.Column('height_cm', sa.Integer(), nullable=True))
    op.add_column('game_wrestlers', sa.Column('weight_kg', sa.Integer(), nullable=True))
    op.add_column('game_wrestlers', sa.Column('body_type', sa.String(length=20), nullable=True))
    op.add_column('game_wrestlers', sa.Column('kayfabe_commitment', sa.Integer(), nullable=True))
    op.add_column('game_wrestlers', sa.Column('social_media_following', sa.Integer(), nullable=True))
    op.add_column('game_wrestlers', sa.Column('public_perception', sa.String(length=30), nullable=True))
    op.add_column('game_wrestlers', sa.Column('character_depth', sa.Integer(), nullable=True))
    op.add_column('game_wrestlers', sa.Column('gimmick_changes', sa.Integer(), nullable=True))
    op.add_column('game_wrestlers', sa.Column('kayfabe_break_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_narrative_logs_agent_id'), 'narrative_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_narrative_logs_time_index'), 'narrative_logs', ['time_index'], unique=False)
    op.create_index('ix_narrative_tick_time', 'narrative_logs', ['tick_id', 'time_index'], unique=False)
    op.create_index('ix_shows_world_completed', 'shows', ['world_id', 'is_completed'], unique=False)
    op.create_index('ix_shows_world_date', 'shows', ['world_id', 'game_date'], unique=False)
    op.add_column('storylines', sa.Column('kayfabe_level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='player', nullable=False))
    op.add_column('users', sa.Column('api_key', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.add_column('wrestler_stats', sa.Column('cage_specialist', sa.Integer(), nullable=True))
    op.add_column('wrestler_stats', sa.Column('ladder_specialist', sa.Integer(), nullable=True))
    op.add_column('wrestler_stats', sa.Column('hardcore_specialist', sa.Integer(), nullable=True))
    op.add_column('wrestler_stats', sa.Column('conditioning_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wrestler_stats', 'conditioning_level')
    op.drop_column('wrestler_stats', 'hardcore_specialist')
    op.drop_column('wrestler_stats', 'ladder_specialist')
    op.drop_column('wrestler_stats', 'cage_specialist')
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_column('users', 'api_key')
    op.drop_column('users', 'role')
    op.drop_column('storylines', 'kayfabe_level')
    op.drop_index('ix_shows_world_date', table_name='shows')
    op.drop_index('ix_shows_world_completed', table_name='shows')
    op.drop_index('ix_narrative_tick_time', table_name='narrative_logs')
    op.drop_index(op.f('ix_narrative_logs_time_index'), table_name='narrative_logs')
    op.drop_index(op.f('ix_narrative_logs_agent_id'), table_name='narrative_logs')
    op.drop_column('game_wrestlers', 'kayfabe_break_count')
    op.drop_column('game_wrestlers', 'gimmick_changes')
    op.drop_column('game_wrestlers', 'character_depth')
    op.drop_column('game_wrestlers', 'public_perception')
    op.drop_column('game_wrestlers', 'social_media_following')
    op.drop_column('game_wrestlers', 'kayfabe_commitment')
    op.drop_column('game_wrestlers', 'body_type')
    op.drop_column('game_wrestlers', 'weight_kg')
    op.drop_column('game_wrestlers', 'height_cm')
    op.drop_column('game_wrestlers', 'is_hall_of_famer')
    op.drop_column('game_wrestlers', 'legacy_score')
    op.drop_column('game_wrestlers', 'creative_influence')
    op.drop_column('game_wrestlers', 'locker_room_standing')
    op.drop_column('game_wrestlers', 'satisfaction')
    op.drop_column('game_wrestlers', 'ring_rust_days')
    op.drop_column('game_wrestlers', 'career_phase')
    op.drop_column('game_wrestlers', 'peak_age')
    op.drop_column('game_wrestlers', 'birth_date')
    op.drop_column('game_wrestlers', 'last_booked_date')
    op.drop_column('game_wrestlers', 'win_streak')
    op.drop_column('game_wrestlers', 'draw_rating')
    op.drop_column('game_wrestlers', 'alignment_momentum')
    op.drop_column('game_federations', 'social_media_policy')
    op.drop_column('game_federations', 'allows_worked_shoots')
    op.drop_column('game_federations', 'kayfabe_strictness')
    op.drop_column('game_federations', 'regional_strength')
    op.drop_column('game_federations', 'fanbase_loyalty')
    op.drop_column('game_federations', 'momentum')
    op.drop_column('game_federations', 'market_share')
    op.drop_index(op.f('ix_engine_requests_status'), table_name='engine_requests')
    op.drop_index(op.f('ix_engine_requests_agent_id'), table_name='engine_requests')
    op.drop_index(op.f('ix_stable_members_wrestler_id'), table_name='stable_members')
    op.drop_index(op.f('ix_stable_members_stable_id'), table_name='stable_members')
    op.drop_table('stable_members')
    op.drop_index(op.f('ix_career_highlights_wrestler_id'), table_name='career_highlights')
    op.drop_table('career_highlights')
    op.drop_index(op.f('ix_stables_world_id'), table_name='stables')
    op.drop_index(op.f('ix_stables_federation_id'), table_name='stables')
    op.drop_index('ix_stable_world_fed', table_name='stables')
    op.drop_table('stables')
    op.drop_index('ix_social_media_world_date', table_name='social_media_posts')
    op.drop_index(op.f('ix_social_media_posts_wrestler_id'), table_name='social_media_posts')
    op.drop_index(op.f('ix_social_media_posts_world_id'), table_name='social_media_posts')
    op.drop_table('social_media_posts')
    op.drop_index(op.f('ix_ppv_events_world_id'), table_name='ppv_events')
    op.drop_index(op.f('ix_ppv_events_federation_id'), table_name='ppv_events')
    op.drop_table('ppv_events')
    op.drop_index(op.f('ix_manager_clients_world_id'), table_name='manager_clients')
    op.drop_index(op.f('ix_manager_clients_manager_id'), table_name='manager_clients')
    op.drop_index(op.f('ix_manager_clients_client_wrestler_id'), table_name='manager_clients')
    op.drop_index('ix_manager_client_world', table_name='manager_clients')
    op.drop_table('manager_clients')
    op.drop_index(op.f('ix_wrestler_relationships_wrestler2_id'), table_name='wrestler_relationships')
    op.drop_index(op.f('ix_wrestler_relationships_wrestler1_id'), table_name='wrestler_relationships')
    op.drop_index(op.f('ix_wrestler_relationships_world_id'), table_name='wrestler_relationships')
    op.drop_index('ix_relationship_pair', table_name='wrestler_relationships')
    op.drop_table('wrestler_relationships')
    op.drop_index(op.f('ix_wrestler_pushes_wrestler_id'), table_name='wrestler_pushes')
    op.drop_index(op.f('ix_wrestler_pushes_world_id'), table_name='wrestler_pushes')
    op.drop_index(op.f('ix_wrestler_pushes_federation_id'), table_name='wrestler_pushes')
    op.drop_table('wrestler_pushes')
    op.drop_index(op.f('ix_wrestler_goals_wrestler_id'), table_name='wrestler_goals')
    op.drop_table('wrestler_goals')
    op.drop_table('wrestler_backstories')
    op.drop_index(op.f('ix_talent_offers_wrestler_id'), table_name='talent_offers')
    op.drop_index(op.f('ix_talent_offers_world_id'), table_name='talent_offers')
    op.drop_index(op.f('ix_talent_offers_federation_id'), table_name='talent_offers')
    op.drop_table('talent_offers')
    op.drop_index(op.f('ix_tag_teams_wrestler2_id'), table_name='tag_teams')
    op.drop_index(op.f('ix_tag_teams_wrestler1_id'), table_name='tag_teams')
    op.drop_index(op.f('ix_tag_teams_world_id'), table_name='tag_teams')
    op.drop_table('tag_teams')
    op.drop_index(op.f('ix_mentorships_world_id'), table_name='mentorships')
    op.drop_index(op.f('ix_mentorships_protege_id'), table_name='mentorships')
    op.drop_index(op.f('ix_mentorships_mentor_id'), table_name='mentorships')
    op.drop_index(op.f('ix_mentorships_federation_id'), table_name='mentorships')
    op.drop_table('mentorships')
    op.drop_index(op.f('ix_managers_world_id'), table_name='managers')
    op.drop_index(op.f('ix_managers_federation_id'), table_name='managers')
    op.drop_table('managers')
    op.drop_index(op.f('ix_life_events_wrestler_id'), table_name='life_events')
    op.drop_index(op.f('ix_life_events_world_id'), table_name='life_events')
    op.drop_index('ix_life_event_world_date', table_name='life_events')
    op.drop_table('life_events')
    op.drop_index(op.f('ix_hall_of_fame_wrestler_id'), table_name='hall_of_fame')
    op.drop_index(op.f('ix_hall_of_fame_world_id'), table_name='hall_of_fame')
    op.drop_table('hall_of_fame')
    op.drop_index(op.f('ix_gimmick_history_wrestler_id'), table_name='gimmick_history')
    op.drop_table('gimmick_history')
    op.drop_index(op.f('ix_booking_visions_world_id'), table_name='booking_visions')
    op.drop_table('booking_visions')
    op.drop_index('ix_audit_world_ts', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_world_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
