# Models package for LLMFed
# Import all model modules so Base.metadata captures all tables and expose the
# compatibility surface used throughout the application.
from models.db_models import (
    Base,
    AgentDB,
    FederationDB,
    EngineRequestDB,
    NarrativeLogDB,
)
from models.game_models import (
    UserDB,
    PlayerDB,
    WorldDB,
    WorldStateDB,
    GameFederationDB,
    GameWrestlerDB,
    WrestlerStatsDB,
    ContractDB,
    ShowDB,
    ShowSegmentDB,
    MatchDB,
    MatchParticipantDB,
    MatchEventDB,
    PromoDB,
    ChampionshipDB,
    ChampionshipHistoryDB,
    StorylineDB,
    StorylineParticipantDB,
    PlayerActionDB,
    GameNarrativeLogDB,
    WorldNewsDB,
    WrestlerHistoryDB,
    WrestlerRelationshipDB,
    TagTeamDB,
    TalentOfferDB,
)

__all__ = [
    "Base",
    "AgentDB",
    "FederationDB",
    "EngineRequestDB",
    "NarrativeLogDB",
    "UserDB",
    "PlayerDB",
    "WorldDB",
    "WorldStateDB",
    "GameFederationDB",
    "GameWrestlerDB",
    "WrestlerStatsDB",
    "ContractDB",
    "ShowDB",
    "ShowSegmentDB",
    "MatchDB",
    "MatchParticipantDB",
    "MatchEventDB",
    "PromoDB",
    "ChampionshipDB",
    "ChampionshipHistoryDB",
    "StorylineDB",
    "StorylineParticipantDB",
    "PlayerActionDB",
    "GameNarrativeLogDB",
    "WorldNewsDB",
    "WrestlerHistoryDB",
    "WrestlerRelationshipDB",
    "TagTeamDB",
    "TalentOfferDB",
]
